language: php
php: 
 - '7.0'

before_script:
 - git checkout -qf master
 - git remote set-url origin https://Pogogo007:$PASSWORD@github.com/Pogogo007/Elo.git
 - git config --global user.email "travis@travis.com"
 - git config --global user.name "Travis"
 - git rm Elo*.phar

script:
 - cd /home/travis/build/Pogogo007
 - php Elo/mkplugin.php Elo Elo/src
 - cat Elo*.phar
 - cd /home/travis/build/Pogogo007/Elo
 - mv /home/travis/build/Pogogo007/Elo*.phar /home/travis/build/Pogogo007/Elo/
 - git remote set-url origin https://Pogogo007:$PASSWORD@github.com/Pogogo007/Elo.git
 - git add Elo*.phar
 - git commit -m "Auto Phar Travis Complete [ci skip]"
 - git push origin master
