language: php
php: 
 - '7.0'

script:
 - cd /home/travis/build/Pogogo007
 - php Elo/mkplugin.php Elo Elo/src
 - cd /home/travis/build/Pogogo007/Elo
 - git config --global user.email "builds@travis-ci.com"
 - git config --global user.name "Travis CI"
 - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
 - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
 - git push -q https://$TAGPERM@github.com/Pogogo007/Elo --tags

deploy:
  provider: releases
  file: "Elo*.phar"
  skip_cleanup: true
  on:
    tags: true
    
