#Coins The Player Starts With
Starting-Cons: 100
# Choose if Coins loss on death
Lose-Coins-onDeath: true
# Amount of Coins Lost on Death
Death-Coins-Loss: 10 #Can be set to 0 for mini games using the API and such
# Choose if win coins on kill
Get-Coins-On-Kill: true
# Amount of Coins Gained on Kill
Coins-On-Kill: 100
